name: akhelper

on:
  workflow_dispatch:
  push:
    paths:
      - "casaos/**"
      - ".github/workflows/casaos.yml"
      - "!**/README.md"

env:
  REGISTRY: ghcr.io
  HUB_NAME: moomiji/casaos
  PLATFORMS: linux/amd64, linux/arm64, linux/arm/v7
  IMAGE_NAME: casaos

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

      - name: Metadata for images
        id: metadata
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.HUB_NAME }}
          tags: type=raw,value=latest

      - name: Login to REGISTRY
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ${{ env.IMAGE_NAME }}/
          file: ${{ env.IMAGE_NAME }}/Dockerfile
          platforms: ${{ env.PLATFORMS }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
