name: test

on:
  workflow_dispatch:
env:
  IMAGE_NAME: testhub
  PLATFORMS: linux/amd64
  username: ${{ github.actor }}
  password: ${{ secrets.GITHUB_TOKEN }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

      - name: Metadata for images
        id: metadata
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.username }}/${{ env.IMAGE_NAME }}
          tags: type=raw,value=latest

      - name: Login to REGISTRY
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: casaos/
          file: casaos/Dockerfile
          platforms: ${{ env.PLATFORMS }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}

      - name: ddtv/deps
        uses: christian-korneck/update-container-description-action@v1
        env:
          DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKERHUB_PASSWORD }}
        with:
          destination_container_repo: moomiji/testhub
          short_description: '测试用仓库'
